[project]
name = "slsrv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.124.0",
    "httpie>=3.2.4",
    "numpy>=2.3.5",
    "pydantic>=2.12.5",
    "tinydb>=4.8.2",
    "uvicorn>=0.38.0",
]
